@echo off
echo Running JavaFX application...
java --module-path "C:\Program Files\Java\javafx-sdk-23.0.2\lib" --add-modules javafx.controls,javafx.fxml,javafx.graphics,javafx.media -cp bin application.MainApp